### ISSUE TITLE
 Voice recognition function that worked with vosk in the original..

### ISSUE THREAD

**Issue by tlsrl8271** [FENRlR/ChatWaifu-iSTFT-VITS#1]
https://github.com/openai/whisper

Is it difficult to operate with whisper voice recognition?

I've been trying to change for a week now...

**Comment by FENRlR** [comment]
The actual original source of this repository is https://github.com/ouor/ChatWaifu-API, which was based on the old version of https://github.com/cjyaddone/ChatWaifuL2D. So I didn't expect such aspects.

As this is just an end-to-end system, adding voice recognition would not be that difficult.  I'll give it a try soon.

**Comment by tlsrl8271** [comment]
OMG..sir thank you so much..!

**Comment by FENRlR** [comment]
Added voice recognition via openai-whisper.

The input sequence ends when there is an empty input (silence) for 3 seconds.
I tested it with my old webcam microphone, but I'm not sure if it would have the same response on other devices.
So you may need to manually edit the threshold variable to define an empty input that fits on your device.

**Comment by tlsrl8271** [comment]
Thank you so much for taking the time to add voice recognition! I'm reinstalling to try voice recognition, and I get a couple of errors

Why do I get this error?
./userfile/tts/
Other than putting in the model that I got here
https://github.com/CjangCjengh/TtSModels

Is there anything else I need to do?

CMD
(.venv) C:\Users\pc\ChatWaifu-iSTFT-VITS>python Server.py
C:\Users\pc\ChatWaifu-iSTFT-VITS\.venv\lib\site-packages\whisper\timing.py:58: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def backtrace(trace: np.ndarray):
Waiting connection from client...
Connected.
Selected language : kor
Traceback (most recent call last):
  File "Server.py", line 340, in <module>
    main()
  File "Server.py", line 199, in main
    tts = vits(model_path, config_path)
  File "Server.py", line 56, in __init__
    self.net_g_ms = SynthesizerTrn(
TypeError: __init__() missing 2 required positional arguments: 'gen_istft_n_fft' and 'gen_istft_hop_size'

renpy

While running game code:
  File "script.rpy", line 63, in script
    python:
  File "script.rpy", line 64, in <module>
    client.send(("1").encode())
ConnectionAbortedError: [WinError 10053] 현재 연결은 사용자의 호스트 시스템의 소프트웨어의 의해 중단되었습니다

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "script.rpy", line 63, in script
    python:
  File "C:\Users\pc\Desktop\renpy-8.0.3-sdk\renpy\ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\pc\Desktop\renpy-8.0.3-sdk\renpy\python.py", line 1061, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "script.rpy", line 64, in <module>
    client.send(("1").encode())
ConnectionAbortedError: [WinError 10053] 현재 연결은 사용자의 호스트 시스템의 소프트웨어의 의해 중단되었습니다

Windows-10-10.0.19045 AMD64
Ren'Py 8.0.3.22090809
ChatWithGPT 1.0
Fri Jul  7 01:36:47 2023
```

**Comment by FENRlR** [comment]
Just as the title of this repository suggests, the supported format of VITS model here is iSTFT-VITS (based on https://github.com/misakiudon/MB-iSTFT-VITS-multilingual), which is a bit different from original VITS and you can confirm it by the following error : 
```
TypeError: init() missing 2 required positional arguments: 'gen_istft_n_fft' and 'gen_istft_hop_size'. 
``` 
Which occurred due to other configuration arguments that it requires.

It would not be impossible to add support for other VITS models by separating inference but I have no plans, at least for now.
